### ISSUE TITLE
Ubrzavanje Sneška

### ISSUE THREAD

**Issue by ivan-cukic-matf** [MATF-RG17/RG080-snowman#3]
Stavite da se Sneško kreće sve brže kako vreme prolazi (posle #2)

**Comment by ninkovicr** [comment]
Dodala sam tri nivoa, nivo se bira prilikom pokretanje kao argument komandne linije.
1 za lak, 2 za srednji i 3 za tezak.
I Snesko se ubrzava kako vreme teze.
